featureMeta:
  doc:
    description: the short name of the document (m-code)
  colId:
    description: collection id
  docId:
    description: document id
  title:
    description: document title
  title@la:
    description: document title in Latin
  title@nl:
    description: document title in Dutch
  title@fr:
    description: document title in French
  title@es:
    description: document title in Spanish
  author:
    description: author of document; if multiple they are given separated by commas
  publisher:
    description: publisher of document; if multiple they are given separated by commas
  place:
    description: place of publisher of document; if multiple they are given separated by commas
  uploader:
    description: person that uploaded the images to the OCR engine
  certainty@la:
    description: certainty of the Latin title
  certainty@nl:
    description: certainty of the Dutch title
  certainty@fr:
    description: certainty of the French title
  certainty@es:
    description: certainty of the Spanish title
  url:
    description: web location of the first page of the scan
  earliest:
    description: earliest date of the document
  latest:
    description: latest date of the document
  form:
    description: form of the document
  form_type:
    description: form type of the document
  is_anonymous:
    description: whether the document is anonymous
  genre:
    description: genre of the document
  subgenre:
    description: subgenre of the document
  certainty:
    description: certainty of whether the document is a manifest of the given expression and work
  expression:
    description: the expression the document is a manifesation of
  work:
    description: the work the document is a manifesation of
  has_dramaweb_scan:
    description: whether there is a scan on dramaweb
  has_dramaweb_transcription:
    description: whether there is a transcription on dramaweb
  ceneton_scan:
    description: releated url into Ceneton scan(s)
  ceneton_transcription:
    description: releated url into Ceneton transcription(s)
  external_scan:
    description: releated url into external scan(s)
  external_transcription:
    description: releated url into external transcription(s)
  remarks:
    description: remarks about the coupling to expressions/works
  link_ub_antwerp:
    description: link to the University Library Antwerp
  link_kbb:
    description: link to the Royal Library Belgium (KBR)
  link_ub_gent:
    description: link to the University Library Ghent
  link_bnf:
    description: link to the National Library France (BnF)
  link_kb:
    description: link to the Royal Library Netyherlands (KB)
  link_google:
    description: link to Google Books
  link_bll:
    description: link to the British Library
