locations:
  repoBase: ~/gitlab.huc.knaw.nl/translatin/corpus

sourceVersion: "0.1"

langMap:
  Latin: la
  Dutch: nl
  French: fr
  Spanish: es

metadata:
  file: metadata.xml
  otherFiles:
    - mets.xml

  elems:
    - title
    - colId
    - docId
    - url
    - uploader
  dbElems:
    - title@la
    - title@nl
    - title@fr
    - title@es
    - certainty
    - certainty@la
    - certainty@nl
    - certainty@fr
    - certainty@es
    - author
    - publisher
    - place
    - earliest
    - latest
    - form
    - form_type
    - is_anonymous
    - genre
    - subgenre
    - has_dramaweb_scan
    - has_dramaweb_transcription
    - ceneton_scan
    - ceneton_transcription
    - external_scan
    - external_transcription
    - remarks
    - link_ub_antwerp
    - link_kbb
    - link_ub_gent
    - link_bnf
    - link_kb
    - link_google
    - link_bll
    - expression
    - work

  sourceTables:
    - manifestations
    - manifestation_titles
    - expressions
    - works
    - expression_manifestations
    - work_expressions
    - authors
    - authors_manifestations
    - publishers
    - manifestations_publishers
    - places

skipDocs:
  - M256
  - M257
  - M258
  - M259
  - M260
